name: test-flow
on:[push]

jobs:
	build:
		runs-on: ubuntu-latest
		steps:
			-name: checkout code
			 uses: actions/checkout@v2
			-name: list the file
			 run: |
				ls -ltr; mkdir test_folder; ls -ltr
